###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    mysql:
        image: 'mysql:8.0'
        working_dir: /application
        volumes:
            - '.:/application'
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=db_laravel_banco_dados
            - MYSQL_USER=secret
            - MYSQL_PASSWORD=secret
        ports:
            - '23002:3306'

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - './api:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '23000:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /application
        volumes:
            - './api:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'
